#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalShopBackEnd
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Pharmacy")]
	public partial class MedicalShopDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MedicalShopDataContext() : 
				base(global::MedicalShopBackEnd.Properties.Settings.Default.PharmacyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MedicalShopDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedicalShopDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedicalShopDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedicalShopDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ManufacturerViewAll")]
		public ISingleResult<ManufacturerViewAllResult> ManufacturerViewAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ManufacturerViewAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProductViewAll")]
		public ISingleResult<ProductViewAllResult> ProductViewAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ProductViewAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProductViewByManufactureId")]
		public ISingleResult<ProductViewByManufactureIdResult> ProductViewByManufactureId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string manufactureId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manufactureId);
			return ((ISingleResult<ProductViewByManufactureIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ProductViewAllByManufactureId")]
		public ISingleResult<ProductViewAllByManufactureIdResult> ProductViewAllByManufactureId([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string manufactureId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manufactureId);
			return ((ISingleResult<ProductViewAllByManufactureIdResult>)(result.ReturnValue));
		}
	}
	
	public partial class ManufacturerViewAllResult
	{
		
		private string _ID;
		
		private string _Name;
		
		private string _Address;
		
		private string _phone;
		
		private string _Email;
		
		private string _Description;
		
		public ManufacturerViewAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	public partial class ProductViewAllResult
	{
		
		private string _ID;
		
		private string _Name;
		
		private string _Group_ID;
		
		private string _Manufacture_ID;
		
		private string _Shelf_ID;
		
		private string _Generic_ID;
		
		private System.Nullable<decimal> _Stock_Minimum_Level;
		
		private System.Nullable<decimal> _Stock_Maximum_Level;
		
		private string _Medicine_For;
		
		private string _Description;
		
		private string _Unit_ID;
		
		public ProductViewAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group ID]", Storage="_Group_ID", DbType="VarChar(50)")]
		public string Group_ID
		{
			get
			{
				return this._Group_ID;
			}
			set
			{
				if ((this._Group_ID != value))
				{
					this._Group_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Manufacture ID]", Storage="_Manufacture_ID", DbType="VarChar(50)")]
		public string Manufacture_ID
		{
			get
			{
				return this._Manufacture_ID;
			}
			set
			{
				if ((this._Manufacture_ID != value))
				{
					this._Manufacture_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Shelf ID]", Storage="_Shelf_ID", DbType="VarChar(50)")]
		public string Shelf_ID
		{
			get
			{
				return this._Shelf_ID;
			}
			set
			{
				if ((this._Shelf_ID != value))
				{
					this._Shelf_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Generic ID]", Storage="_Generic_ID", DbType="VarChar(50)")]
		public string Generic_ID
		{
			get
			{
				return this._Generic_ID;
			}
			set
			{
				if ((this._Generic_ID != value))
				{
					this._Generic_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Stock Minimum Level]", Storage="_Stock_Minimum_Level", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Stock_Minimum_Level
		{
			get
			{
				return this._Stock_Minimum_Level;
			}
			set
			{
				if ((this._Stock_Minimum_Level != value))
				{
					this._Stock_Minimum_Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Stock Maximum Level]", Storage="_Stock_Maximum_Level", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Stock_Maximum_Level
		{
			get
			{
				return this._Stock_Maximum_Level;
			}
			set
			{
				if ((this._Stock_Maximum_Level != value))
				{
					this._Stock_Maximum_Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Medicine For]", Storage="_Medicine_For", DbType="VarChar(MAX)")]
		public string Medicine_For
		{
			get
			{
				return this._Medicine_For;
			}
			set
			{
				if ((this._Medicine_For != value))
				{
					this._Medicine_For = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Unit ID]", Storage="_Unit_ID", DbType="VarChar(50)")]
		public string Unit_ID
		{
			get
			{
				return this._Unit_ID;
			}
			set
			{
				if ((this._Unit_ID != value))
				{
					this._Unit_ID = value;
				}
			}
		}
	}
	
	public partial class ProductViewByManufactureIdResult
	{
		
		private string _productId;
		
		private string _productName;
		
		private string _manufactureId;
		
		public ProductViewByManufactureIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string productId
		{
			get
			{
				return this._productId;
			}
			set
			{
				if ((this._productId != value))
				{
					this._productId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productName", DbType="VarChar(MAX)")]
		public string productName
		{
			get
			{
				return this._productName;
			}
			set
			{
				if ((this._productName != value))
				{
					this._productName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manufactureId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string manufactureId
		{
			get
			{
				return this._manufactureId;
			}
			set
			{
				if ((this._manufactureId != value))
				{
					this._manufactureId = value;
				}
			}
		}
	}
	
	public partial class ProductViewAllByManufactureIdResult
	{
		
		private string _productId;
		
		private string _productName;
		
		private System.Nullable<decimal> _purchaseRate;
		
		private System.Nullable<decimal> _MRP;
		
		private System.Nullable<long> _Pack;
		
		private System.Nullable<int> _unit;
		
		private System.Nullable<bool> _Active;
		
		private string _manufactureId;
		
		public ProductViewAllByManufactureIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string productId
		{
			get
			{
				return this._productId;
			}
			set
			{
				if ((this._productId != value))
				{
					this._productId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_productName", DbType="VarChar(MAX)")]
		public string productName
		{
			get
			{
				return this._productName;
			}
			set
			{
				if ((this._productName != value))
				{
					this._productName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_purchaseRate", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> purchaseRate
		{
			get
			{
				return this._purchaseRate;
			}
			set
			{
				if ((this._purchaseRate != value))
				{
					this._purchaseRate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> MRP
		{
			get
			{
				return this._MRP;
			}
			set
			{
				if ((this._MRP != value))
				{
					this._MRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pack", DbType="BigInt")]
		public System.Nullable<long> Pack
		{
			get
			{
				return this._Pack;
			}
			set
			{
				if ((this._Pack != value))
				{
					this._Pack = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit", DbType="Int")]
		public System.Nullable<int> unit
		{
			get
			{
				return this._unit;
			}
			set
			{
				if ((this._unit != value))
				{
					this._unit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manufactureId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string manufactureId
		{
			get
			{
				return this._manufactureId;
			}
			set
			{
				if ((this._manufactureId != value))
				{
					this._manufactureId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
